### ISSUE TITLE
OSS Team Pricing

### ISSUE THREAD

**Issue by irmerk** [bookworm-reads/documentation#6]
We need to register for OSS pricing in GitHub.

**Comment by ameliagoodman** [comment]
sent a request ticket: https://support.github.com/ticket/personal/0/2539674

**Comment by ameliagoodman** [comment]
<img width="881" alt="Screen Shot 2024-02-04 at 5 11 37 PM" src="https://github.com/bookworm-reads/documentation/assets/16273773/a5b040b1-8d49-43ac-96f5-f0496463e3d9">
looks like they don’t do this anymore? here's what they said
